/**
 * Autonomous Lab — Hypothesis Generator
 * Scans recent experiment outcomes and auto-generates a prioritised backlog
 * of improvement hypotheses that admins can review and promote to actual experiments.
 */
import { prisma } from '@/lib/prisma'
import type { LabModule } from './types'

export interface HypothesisBacklogItem {
  id: string
  module: LabModule
  priority: 'critical' | 'high' | 'medium' | 'low'
  hypothesis: string
  suggestedChanges: string[]
  rationale: string
  status: 'pending' | 'promoted' | 'dismissed'
  autoGenerated: boolean
  impactScore: number
  confidenceScore: number
  costScore: number
  priorityScore: number
  signalSummary: Record<string, unknown>
  generatedAt: string
  updatedAt: string
}

export interface UserFeedbackSignal {
  id: string
  module: LabModule
  feedbackType:
    | 'ranking_good'
    | 'ranking_bad'
    | 'suspicious_firm'
    | 'firm_undervalued'
    | 'firm_overvalued'
    | 'other'
  message: string
  firmId?: string
  weight: number
  trustScore: number
  frequencyScore: number
  recencyScore: number
  antiManipulationFactor: number
  weightedScore: number
  createdAt: string
}

export interface PriorityHypothesisInput {
  module: LabModule
  hypothesis: string
  suggestedChanges: string[]
  rationale: string
  autoGenerated?: boolean
  impactScore?: number
  confidenceScore?: number
  costScore?: number
  priorityScore?: number
  priority?: HypothesisBacklogItem['priority']
  signalSummary?: Record<string, unknown>
}

const FEEDBACK_RECENCY_HALF_LIFE_DAYS = 7

function clamp(value: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, value))
}

function normalizeTrustScore(context: Record<string, unknown> | null | undefined): number {
  const raw = context?.userTrustScore ?? context?.trustScore ?? 1
  return clamp(Number(raw) || 1, 0.25, 3)
}

function recencyScoreFromIso(createdAt: string, now = Date.now()): number {
  const created = new Date(createdAt).getTime()
  if (!Number.isFinite(created)) return 1
  const ageDays = Math.max(0, (now - created) / (1000 * 60 * 60 * 24))
  const decay = Math.exp((-Math.log(2) * ageDays) / FEEDBACK_RECENCY_HALF_LIFE_DAYS)
  return clamp(Number(decay.toFixed(4)), 0.15, 1)
}

function frequencyScoreFromCount(count: number): number {
  if (count <= 1) return 1
  return clamp(Number((1 + Math.log2(count) * 0.35).toFixed(4)), 1, 2.5)
}

function buildWeightedFeedbackSignal(input: {
  weight: number
  trustScore: number
  frequencyCount: number
  actorFrequencyCount?: number
  createdAt: string
}): {
  trustScore: number
  frequencyScore: number
  recencyScore: number
  antiManipulationFactor: number
  weightedScore: number
} {
  const trustScore = clamp(Number(input.trustScore || 1), 0.25, 3)
  const frequencyScore = frequencyScoreFromCount(input.frequencyCount)
  const recencyScore = recencyScoreFromIso(input.createdAt)
  const actorFrequency = Math.max(1, Number(input.actorFrequencyCount || 1))
  const antiManipulationFactor =
    actorFrequency > 5
      ? clamp(Number(Math.sqrt(5 / actorFrequency).toFixed(4)), 0.2, 1)
      : 1
  const weightedScore = Number(
    (
      Number(input.weight || 1) *
      trustScore *
      frequencyScore *
      recencyScore *
      antiManipulationFactor
    ).toFixed(4)
  )

  return {
    trustScore,
    frequencyScore,
    recencyScore,
    antiManipulationFactor,
    weightedScore,
  }
}

function feedbackActorKeyFromContext(
  context: Record<string, unknown> | null | undefined
): string {
  const ip = String(context?.ip || '').trim().toLowerCase()
  const device = String(context?.deviceId || context?.ua || '').trim().toLowerCase()
  if (!ip && !device) return 'anon'
  return `${ip || 'noip'}|${device || 'nodevice'}`
}

// ─── Pattern catalogue ────────────────────────────────────────────────────────
const PATTERNS: Record<
  string,
  Array<{ hypothesis: string; changes: string[]; rationale: string; priority: 'critical' | 'high' | 'medium' | 'low' }>
> = {
  coverageDelta_low: [
    {
      hypothesis: 'Réduire la pénalité N/A pour augmenter la couverture des firmes partiellement documentées',
      changes: ['na_penalty_reduction_v1', 'partial_coverage_boost'],
      rationale: 'La couverture est faible: les firmes partiellement documentées sont trop pénalisées.',
      priority: 'high',
    },
    {
      hypothesis: 'Activer un mode de scoring dégradé (plancher minimal) pour les firmes avec 50%+ de données manquantes',
      changes: ['degraded_mode_50pct', 'minimum_score_floor'],
      rationale: 'Un plancher minimal de score permettrait de couvrir plus de firmes au lieu de les exclure.',
      priority: 'medium',
    },
  ],
  stabilityDelta_low: [
    {
      hypothesis: 'Appliquer un lissage exponentiel (EMA) sur les scores pour réduire la variance inter-run',
      changes: ['ema_smoothing_v1', 'score_damping_factor_0_2'],
      rationale: 'La variance entre runs est élevée. Un EMA alpha=0.2 réduirait le bruit sans lag excessif.',
      priority: 'high',
    },
    {
      hypothesis: 'Relever le seuil de similarité de données requis pour déclencher une mise à jour de score',
      changes: ['update_threshold_v2', 'similarity_gate_5pct'],
      rationale: 'Les scores fluctuent parce que de petites variations de données induisent des recalculs inutiles.',
      priority: 'medium',
    },
  ],
  anomaliesDelta_low: [
    {
      hypothesis: 'Resserrer les plages de validation des métriques de paiement pour éliminer les outliers extrêmes',
      changes: ['payout_range_tighten_v1', 'outlier_clamp_3sigma'],
      rationale: 'La majorité des anomalies proviennent de métriques de paiement hors-plage.',
      priority: 'critical',
    },
    {
      hypothesis: 'Ajouter une gate de validation stricte sur les scores > 95 ou < 5',
      changes: ['extreme_score_gate', 'validation_bounds_v2'],
      rationale: 'Scores extrêmes indiquent souvent des erreurs de données en amont.',
      priority: 'high',
    },
  ],
  riskSeparationDelta_low: [
    {
      hypothesis: 'Augmenter le poids du pilier risk_model pour améliorer la séparation High/Medium/Low',
      changes: ['risk_model_weight_1_5x', 'bucket_boundary_v2'],
      rationale: 'Les buckets de risque se confondent. Renforcer le pilier risque devrait clarifier la séparation.',
      priority: 'high',
    },
    {
      hypothesis: 'Élargir les marges de séparation entre les seuils de bucket (25/50/75 → 20/50/80)',
      changes: ['bucket_threshold_widen_v1'],
      rationale: 'Des marges plus larges réduiraient les zones d\'ambiguité entre niveaux de risque.',
      priority: 'medium',
    },
  ],
  webgl_perf_low: [
    {
      hypothesis: 'Activer le LOD adaptatif pour réduire la résolution du globe sur les appareils à faible GPU',
      changes: ['lod_adaptive_v1', 'globe_res_tier_auto'],
      rationale: 'FPS insuffisant sur certains clients. Un LOD adaptatif devrait améliorer les performances moyennes.',
      priority: 'medium',
    },
  ],
  high_rejection_rate: [
    {
      hypothesis: 'Réduire le candidateBias par défaut (de 1.1 à 1.0) pour produire des candidats moins agressifs',
      changes: ['candidateBias_1_0', 'conservative_mode'],
      rationale: 'Le taux de rejet élevé suggère que les candidats sont trop éloignés de la baseline.',
      priority: 'high',
    },
  ],
  generic_scoring: [
    {
      hypothesis: 'Tester une pondération plus équilibrée entre piliers ESG (governance +10%, environment -5%)',
      changes: ['pillar_rebalance_v1', 'governance_boost_10pct'],
      rationale: 'Hypothèse générique de départ pour explorer l\'espace des paramètres.',
      priority: 'low',
    },
  ],
}

// ─── DB setup ─────────────────────────────────────────────────────────────────
async function ensureSchema(): Promise<void> {
  await prisma.$executeRawUnsafe(`
    CREATE TABLE IF NOT EXISTS autonomous_hypothesis_backlog (
      id TEXT PRIMARY KEY,
      module TEXT NOT NULL,
      priority TEXT NOT NULL DEFAULT 'medium',
      hypothesis TEXT NOT NULL,
      suggested_changes JSONB NOT NULL DEFAULT '[]'::jsonb,
      rationale TEXT NOT NULL DEFAULT '',
      status TEXT NOT NULL DEFAULT 'pending',
      auto_generated BOOLEAN NOT NULL DEFAULT true,
      impact_score DOUBLE PRECISION NOT NULL DEFAULT 1,
      confidence_score DOUBLE PRECISION NOT NULL DEFAULT 1,
      cost_score DOUBLE PRECISION NOT NULL DEFAULT 1,
      priority_score DOUBLE PRECISION NOT NULL DEFAULT 1,
      signal_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
      generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  `)
  await prisma.$executeRawUnsafe(`
    ALTER TABLE autonomous_hypothesis_backlog
      ADD COLUMN IF NOT EXISTS impact_score DOUBLE PRECISION NOT NULL DEFAULT 1,
      ADD COLUMN IF NOT EXISTS confidence_score DOUBLE PRECISION NOT NULL DEFAULT 1,
      ADD COLUMN IF NOT EXISTS cost_score DOUBLE PRECISION NOT NULL DEFAULT 1,
      ADD COLUMN IF NOT EXISTS priority_score DOUBLE PRECISION NOT NULL DEFAULT 1,
      ADD COLUMN IF NOT EXISTS signal_summary JSONB NOT NULL DEFAULT '{}'::jsonb
  `)
  await prisma.$executeRawUnsafe(`
    CREATE INDEX IF NOT EXISTS idx_hyp_backlog_module_status
    ON autonomous_hypothesis_backlog(module, status, generated_at DESC)
  `)
  await prisma.$executeRawUnsafe(`
    CREATE INDEX IF NOT EXISTS idx_hyp_backlog_priority
    ON autonomous_hypothesis_backlog(priority_score DESC, generated_at DESC)
  `)

  await prisma.$executeRawUnsafe(`
    CREATE TABLE IF NOT EXISTS autonomous_user_feedback (
      id TEXT PRIMARY KEY,
      module TEXT NOT NULL,
      feedback_type TEXT NOT NULL,
      message TEXT NOT NULL,
      firm_id TEXT,
      weight DOUBLE PRECISION NOT NULL DEFAULT 1,
      context JSONB NOT NULL DEFAULT '{}'::jsonb,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  `)
  await prisma.$executeRawUnsafe(`
    CREATE INDEX IF NOT EXISTS idx_user_feedback_module_time
    ON autonomous_user_feedback(module, created_at DESC)
  `)
}

function normalize(row: Record<string, unknown>): HypothesisBacklogItem {
  return {
    id: String(row.id),
    module: String(row.module) as LabModule,
    priority: String(row.priority) as HypothesisBacklogItem['priority'],
    hypothesis: String(row.hypothesis),
    suggestedChanges: Array.isArray(row.suggested_changes)
      ? (row.suggested_changes as unknown[]).map(String)
      : [],
    rationale: String(row.rationale ?? ''),
    status: String(row.status) as HypothesisBacklogItem['status'],
    autoGenerated: Boolean(row.auto_generated ?? true),
    impactScore: Number(row.impact_score ?? 1),
    confidenceScore: Number(row.confidence_score ?? 1),
    costScore: Number(row.cost_score ?? 1),
    priorityScore: Number(row.priority_score ?? 1),
    signalSummary:
      typeof row.signal_summary === 'object' && row.signal_summary !== null
        ? (row.signal_summary as Record<string, unknown>)
        : {},
    generatedAt:
      row.generated_at instanceof Date
        ? row.generated_at.toISOString()
        : String(row.generated_at),
    updatedAt:
      row.updated_at instanceof Date
        ? row.updated_at.toISOString()
        : String(row.updated_at),
  }
}

function priorityFromScore(score: number): HypothesisBacklogItem['priority'] {
  if (score >= 70) return 'critical'
  if (score >= 55) return 'high'
  if (score >= 35) return 'medium'
  return 'low'
}

function scoreHypothesis(input: {
  module: string
  spot: string
  suggestedChanges: string[]
  basePriority: HypothesisBacklogItem['priority']
  weaknessFrequency: number
  feedbackWeight: number
}): {
  impactScore: number
  confidenceScore: number
  costScore: number
  priorityScore: number
  priority: HypothesisBacklogItem['priority']
  signalSummary: Record<string, unknown>
} {
  const baseImpactByPriority: Record<HypothesisBacklogItem['priority'], number> = {
    critical: 9,
    high: 7,
    medium: 5,
    low: 3,
  }

  const spotImpactBoost: Record<string, number> = {
    anomaliesDelta_low: 1.4,
    stabilityDelta_low: 1.2,
    riskSeparationDelta_low: 1.1,
    coverageDelta_low: 1,
    webgl_perf_low: 1.1,
    high_rejection_rate: 1.3,
    generic_scoring: 0.8,
  }

  const impactScore = Math.min(
    10,
    baseImpactByPriority[input.basePriority] * (spotImpactBoost[input.spot] ?? 1)
  )

  const confidenceScore = Math.max(
    1,
    Math.min(
      10,
      4 + input.weaknessFrequency * 3 + Math.min(3, input.feedbackWeight * 0.4)
    )
  )

  const costScore = Math.max(
    1,
    Math.min(10, 1.5 + input.suggestedChanges.length * 1.4 + (input.module === 'webgl' ? 1.2 : 0))
  )

  const priorityScore = Math.max(
    1,
    Math.min(100, Number(((impactScore * confidenceScore) / costScore * 10).toFixed(2)))
  )

  return {
    impactScore: Number(impactScore.toFixed(2)),
    confidenceScore: Number(confidenceScore.toFixed(2)),
    costScore: Number(costScore.toFixed(2)),
    priorityScore,
    priority: priorityFromScore(priorityScore),
    signalSummary: {
      formula: 'impact * confidence / cost * 10',
      weaknessFrequency: Number(input.weaknessFrequency.toFixed(3)),
      feedbackWeight: Number(input.feedbackWeight.toFixed(3)),
      spot: input.spot,
    },
  }
}

export async function recordUserFeedback(input: {
  module: LabModule
  feedbackType: UserFeedbackSignal['feedbackType']
  message: string
  firmId?: string
  weight?: number
  context?: Record<string, unknown>
}): Promise<UserFeedbackSignal> {
  await ensureSchema()
  const id = `fb_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`
  const weight = Math.max(0.2, Math.min(5, Number(input.weight ?? 1)))

  const rows = await prisma.$queryRawUnsafe<Record<string, unknown>[]>(
    `INSERT INTO autonomous_user_feedback
     (id, module, feedback_type, message, firm_id, weight, context)
     VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb)
     RETURNING *`,
    id,
    input.module,
    input.feedbackType,
    input.message,
    input.firmId ?? null,
    weight,
    JSON.stringify(input.context ?? {})
  )

  const row = rows[0]
  const context =
    typeof row.context === 'object' && row.context !== null
      ? (row.context as Record<string, unknown>)
      : input.context ?? {}
  const trustScore = normalizeTrustScore(context)
  const signal = buildWeightedFeedbackSignal({
    weight: Number(row.weight ?? 1),
    trustScore,
    frequencyCount: 1,
    actorFrequencyCount: 1,
    createdAt:
      row.created_at instanceof Date
        ? row.created_at.toISOString()
        : String(row.created_at),
  })

  return {
    id: String(row.id),
    module: String(row.module) as LabModule,
    feedbackType: String(row.feedback_type) as UserFeedbackSignal['feedbackType'],
    message: String(row.message),
    firmId: row.firm_id ? String(row.firm_id) : undefined,
    weight: Number(row.weight ?? 1),
    trustScore: signal.trustScore,
    frequencyScore: signal.frequencyScore,
    recencyScore: signal.recencyScore,
    antiManipulationFactor: signal.antiManipulationFactor,
    weightedScore: signal.weightedScore,
    createdAt:
      row.created_at instanceof Date
        ? row.created_at.toISOString()
        : String(row.created_at),
  }
}

export async function listRecentUserFeedback(limit = 100): Promise<UserFeedbackSignal[]> {
  await ensureSchema()
  const rows = await prisma.$queryRawUnsafe<Record<string, unknown>[]>(
    `SELECT * FROM autonomous_user_feedback
     ORDER BY created_at DESC LIMIT $1`,
    Math.max(1, Math.min(500, limit))
  )

  const frequencyByKey = rows.reduce<Record<string, number>>((acc, row) => {
    const key = [row.module, row.feedback_type, row.firm_id ?? 'global'].join('::')
    acc[key] = (acc[key] ?? 0) + 1
    return acc
  }, {})

  const actorFrequencyByKey = rows.reduce<Record<string, number>>((acc, row) => {
    const context =
      typeof row.context === 'object' && row.context !== null
        ? (row.context as Record<string, unknown>)
        : {}
    const actorKey = feedbackActorKeyFromContext(context)
    const key = [row.module, row.feedback_type, actorKey].join('::')
    acc[key] = (acc[key] ?? 0) + 1
    return acc
  }, {})

  return rows.map((row) => {
    const createdAt =
      row.created_at instanceof Date
        ? row.created_at.toISOString()
        : String(row.created_at)
    const context =
      typeof row.context === 'object' && row.context !== null
        ? (row.context as Record<string, unknown>)
        : {}
    const frequencyCount =
      frequencyByKey[[row.module, row.feedback_type, row.firm_id ?? 'global'].join('::')] ?? 1
    const signal = buildWeightedFeedbackSignal({
      weight: Number(row.weight ?? 1),
      trustScore: normalizeTrustScore(context),
      frequencyCount,
      actorFrequencyCount:
        actorFrequencyByKey[
          [row.module, row.feedback_type, feedbackActorKeyFromContext(context)].join('::')
        ] ?? 1,
      createdAt,
    })

    return {
      id: String(row.id),
      module: String(row.module) as LabModule,
      feedbackType: String(row.feedback_type) as UserFeedbackSignal['feedbackType'],
      message: String(row.message),
      firmId: row.firm_id ? String(row.firm_id) : undefined,
      weight: Number(row.weight ?? 1),
      trustScore: signal.trustScore,
      frequencyScore: signal.frequencyScore,
      recencyScore: signal.recencyScore,
      antiManipulationFactor: signal.antiManipulationFactor,
      weightedScore: signal.weightedScore,
      createdAt,
    }
  })
}

// ─── Public API ───────────────────────────────────────────────────────────────
export async function listBacklog(
  module?: LabModule,
  limit = 50
): Promise<HypothesisBacklogItem[]> {
  await ensureSchema()
  if (module) {
    const rows = await prisma.$queryRawUnsafe<Record<string, unknown>[]>(
      `SELECT * FROM autonomous_hypothesis_backlog
       WHERE module = $1 AND status = 'pending'
       ORDER BY
         priority_score DESC,
         CASE priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,
         generated_at DESC
       LIMIT $2`,
      module,
      limit
    )
    return rows.map(normalize)
  }
  const rows = await prisma.$queryRawUnsafe<Record<string, unknown>[]>(
    `SELECT * FROM autonomous_hypothesis_backlog
     WHERE status = 'pending'
     ORDER BY
       priority_score DESC,
       CASE priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,
       generated_at DESC
     LIMIT $1`,
    limit
  )
  return rows.map(normalize)
}

export async function enqueuePriorityHypothesis(
  input: PriorityHypothesisInput
): Promise<HypothesisBacklogItem> {
  await ensureSchema()

  const existing = await prisma.$queryRawUnsafe<Record<string, unknown>[]>(
    `SELECT * FROM autonomous_hypothesis_backlog
     WHERE module = $1 AND hypothesis = $2 AND status = 'pending'
     ORDER BY generated_at DESC LIMIT 1`,
    input.module,
    input.hypothesis
  )

  if (existing[0]) {
    return normalize(existing[0])
  }

  const impactScore = Number(input.impactScore ?? 8)
  const confidenceScore = Number(input.confidenceScore ?? 7)
  const costScore = Number(input.costScore ?? 3)
  const priorityScore = Number(
    input.priorityScore ?? Math.max(1, Math.min(100, Number(((impactScore * confidenceScore) / costScore * 10).toFixed(2))))
  )
  const priority = input.priority ?? priorityFromScore(priorityScore)
  const id = `hyp_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`

  const rows = await prisma.$queryRawUnsafe<Record<string, unknown>[]>(
    `INSERT INTO autonomous_hypothesis_backlog
     (id, module, priority, hypothesis, suggested_changes, rationale, status, auto_generated,
      impact_score, confidence_score, cost_score, priority_score, signal_summary)
     VALUES ($1, $2, $3, $4, $5::jsonb, $6, 'pending', $7, $8, $9, $10, $11, $12::jsonb)
     RETURNING *`,
    id,
    input.module,
    priority,
    input.hypothesis,
    JSON.stringify(input.suggestedChanges),
    input.rationale,
    input.autoGenerated ?? true,
    impactScore,
    confidenceScore,
    costScore,
    priorityScore,
    JSON.stringify(input.signalSummary ?? {})
  )

  return normalize(rows[0])
}

export async function generateHypotheses(): Promise<HypothesisBacklogItem[]> {
  await ensureSchema()

  // Scan recent completed experiments for weakness patterns
  const recent = await prisma.$queryRawUnsafe<
    Array<{ module: string; metrics: Record<string, number>; status: string }>
  >(
    `SELECT module, metrics, status FROM autonomous_experiments
     WHERE status IN ('approved', 'rejected', 'review_required')
     ORDER BY updated_at DESC LIMIT 30`
  )

  const moduleSpots: Record<string, Set<string>> = {}
  const weaknessCountByModuleSpot: Record<string, number> = {}

  for (const exp of recent) {
    const m = exp.module
    const mx = (exp.metrics ?? {}) as Record<string, number>
    if (!moduleSpots[m]) moduleSpots[m] = new Set()

    if ((mx.coverageDelta ?? 0) < 0) {
      moduleSpots[m].add('coverageDelta_low')
      weaknessCountByModuleSpot[`${m}:coverageDelta_low`] = (weaknessCountByModuleSpot[`${m}:coverageDelta_low`] ?? 0) + 1
    }
    if ((mx.stabilityDelta ?? 0) < -0.5) {
      moduleSpots[m].add('stabilityDelta_low')
      weaknessCountByModuleSpot[`${m}:stabilityDelta_low`] = (weaknessCountByModuleSpot[`${m}:stabilityDelta_low`] ?? 0) + 1
    }
    if ((mx.anomaliesDelta ?? 0) < -1) {
      moduleSpots[m].add('anomaliesDelta_low')
      weaknessCountByModuleSpot[`${m}:anomaliesDelta_low`] = (weaknessCountByModuleSpot[`${m}:anomaliesDelta_low`] ?? 0) + 1
    }
    if ((mx.riskSeparationDelta ?? 0) < -0.5) {
      moduleSpots[m].add('riskSeparationDelta_low')
      weaknessCountByModuleSpot[`${m}:riskSeparationDelta_low`] = (weaknessCountByModuleSpot[`${m}:riskSeparationDelta_low`] ?? 0) + 1
    }
    if (m === 'webgl' && (mx.perfDelta ?? 0) < -10 && (mx.perfDelta ?? 0) > -35) {
      moduleSpots[m].add('webgl_perf_low')
      weaknessCountByModuleSpot[`${m}:webgl_perf_low`] = (weaknessCountByModuleSpot[`${m}:webgl_perf_low`] ?? 0) + 1
    }
  }

  // User feedback loop: feed weighted user complaints/praises into hypothesis spots.
  const feedbackRows = await prisma.$queryRawUnsafe<
    Array<{
      module: string
      feedback_type: string
      weight: number
      firm_id: string | null
      created_at: Date | string
      context: Record<string, unknown> | null
    }>
  >(
    `SELECT module, feedback_type, weight, firm_id, created_at, context
     FROM autonomous_user_feedback
     WHERE created_at >= now() - interval '30 days'
     ORDER BY created_at DESC LIMIT 500`
  )

  const feedbackFrequencyByKey = feedbackRows.reduce<Record<string, number>>((acc, row) => {
    const key = [row.module, row.feedback_type, row.firm_id ?? 'global'].join('::')
    acc[key] = (acc[key] ?? 0) + 1
    return acc
  }, {})

  const feedbackActorFrequencyByKey = feedbackRows.reduce<Record<string, number>>((acc, row) => {
    const actorKey = feedbackActorKeyFromContext(row.context)
    const key = [row.module, row.feedback_type, actorKey].join('::')
    acc[key] = (acc[key] ?? 0) + 1
    return acc
  }, {})

  const feedbackWeightByModuleSpot: Record<string, number> = {}
  for (const fb of feedbackRows) {
    const mod = fb.module
    if (!moduleSpots[mod]) moduleSpots[mod] = new Set()

    let mappedSpot: string | null = null
    if (fb.feedback_type === 'ranking_bad') mappedSpot = 'stabilityDelta_low'
    if (fb.feedback_type === 'ranking_good') mappedSpot = 'generic_scoring'
    if (fb.feedback_type === 'firm_undervalued') mappedSpot = 'riskSeparationDelta_low'
    if (fb.feedback_type === 'firm_overvalued') mappedSpot = 'anomaliesDelta_low'
    if (fb.feedback_type === 'suspicious_firm') mappedSpot = 'anomaliesDelta_low'
    if (fb.feedback_type === 'other') mappedSpot = mod === 'webgl' ? 'webgl_perf_low' : 'generic_scoring'

    if (!mappedSpot) continue
    moduleSpots[mod].add(mappedSpot)
    const key = `${mod}:${mappedSpot}`
    const weightedSignal = buildWeightedFeedbackSignal({
      weight: Number(fb.weight ?? 1),
      trustScore: normalizeTrustScore(fb.context),
      frequencyCount:
        feedbackFrequencyByKey[[fb.module, fb.feedback_type, fb.firm_id ?? 'global'].join('::')] ?? 1,
      actorFrequencyCount:
        feedbackActorFrequencyByKey[
          [fb.module, fb.feedback_type, feedbackActorKeyFromContext(fb.context)].join('::')
        ] ?? 1,
      createdAt:
        fb.created_at instanceof Date
          ? fb.created_at.toISOString()
          : String(fb.created_at),
    })
    const signalWeight =
      fb.feedback_type === 'ranking_good'
        ? -Math.abs(weightedSignal.weightedScore) * 0.5
        : weightedSignal.weightedScore
    feedbackWeightByModuleSpot[key] = (feedbackWeightByModuleSpot[key] ?? 0) + signalWeight
  }

  // Detect high rejection rate globally
  const rejCount = recent.filter((e) => e.status === 'rejected').length
  const totalCount = recent.length
  if (totalCount > 5 && rejCount / totalCount > 0.6) {
    const scoringMod = 'scoring'
    if (!moduleSpots[scoringMod]) moduleSpots[scoringMod] = new Set()
    moduleSpots[scoringMod].add('high_rejection_rate')
  }

  // If no experiments yet, seed with generic ones
  if (Object.keys(moduleSpots).length === 0) {
    moduleSpots['scoring'] = new Set(['generic_scoring', 'riskSeparationDelta_low'])
  }

  const generated: HypothesisBacklogItem[] = []
  const existingPending = await prisma.$queryRawUnsafe<Array<{ module: string; hypothesis: string }>>(
    `SELECT module, hypothesis FROM autonomous_hypothesis_backlog WHERE status = 'pending'`
  )
  const existingSet = new Set(existingPending.map((r) => `${r.module}::${r.hypothesis}`))

  for (const [mod, spots] of Object.entries(moduleSpots)) {
    for (const spot of spots) {
      const candidates = (PATTERNS[spot] ?? []).slice(0, 2)
      for (const cand of candidates) {
        const duplicateKey = `${mod}::${cand.hypothesis}`
        if (existingSet.has(duplicateKey)) continue

        const weakFreq = (weaknessCountByModuleSpot[`${mod}:${spot}`] ?? 0) / Math.max(1, recent.length)
        const feedbackWeight = feedbackWeightByModuleSpot[`${mod}:${spot}`] ?? 0
        const scored = scoreHypothesis({
          module: mod,
          spot,
          suggestedChanges: cand.changes,
          basePriority: cand.priority,
          weaknessFrequency: weakFreq,
          feedbackWeight,
        })

        const id = `hyp_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`
        await prisma.$executeRawUnsafe(
          `INSERT INTO autonomous_hypothesis_backlog
           (id, module, priority, hypothesis, suggested_changes, rationale, status, auto_generated,
            impact_score, confidence_score, cost_score, priority_score, signal_summary)
           VALUES ($1, $2, $3, $4, $5::jsonb, $6, 'pending', true, $7, $8, $9, $10, $11::jsonb)
           ON CONFLICT (id) DO NOTHING`,
          id,
          mod,
          scored.priority,
          cand.hypothesis,
          JSON.stringify(cand.changes),
          cand.rationale,
          scored.impactScore,
          scored.confidenceScore,
          scored.costScore,
          scored.priorityScore,
          JSON.stringify(scored.signalSummary)
        )
        generated.push({
          id,
          module: mod as LabModule,
          priority: scored.priority,
          hypothesis: cand.hypothesis,
          suggestedChanges: cand.changes,
          rationale: cand.rationale,
          status: 'pending',
          autoGenerated: true,
          impactScore: scored.impactScore,
          confidenceScore: scored.confidenceScore,
          costScore: scored.costScore,
          priorityScore: scored.priorityScore,
          signalSummary: scored.signalSummary,
          generatedAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        })
        existingSet.add(duplicateKey)
      }
    }
  }

  return generated
}

export async function updateBacklogItemStatus(
  id: string,
  status: 'pending' | 'promoted' | 'dismissed'
): Promise<void> {
  await ensureSchema()
  await prisma.$executeRawUnsafe(
    `UPDATE autonomous_hypothesis_backlog SET status = $2, updated_at = now() WHERE id = $1`,
    id,
    status
  )
}
