import { NextRequest, NextResponse } from 'next/server'
import { requireAdminUser } from '@/lib/admin-api-auth'
import {
  generateHypotheses,
  listBacklog,
  listRecentUserFeedback,
} from '@/lib/autonomous-lab/hypothesis-generator'
import { rankBacklogForExecution } from '@/lib/autonomous-lab/priority-engine'
import { getRadarCycleSignals } from '@/lib/autonomous-lab/radar-bridge'
import { getLatestPriorityScores } from '@/lib/autonomous-lab/priority-history'
import { getDecisionPenaltyMap } from '@/lib/autonomous-lab/decision-memory'
import type { HypothesisBacklogItem } from '@/lib/autonomous-lab/hypothesis-generator'
import type { LabModule } from '@/lib/autonomous-lab/types'

function toInt(value: string | null, fallback: number, min: number, max: number): number {
  const n = Number.parseInt(value || String(fallback), 10)
  if (!Number.isFinite(n)) return fallback
  return Math.max(min, Math.min(max, n))
}

function backlogKey(item: { id: string; module: string; hypothesis: string }): string {
  return `${item.id}::${item.module}::${item.hypothesis}`
}

function radarVirtualItem(input: {
  index: number
  module: LabModule
  hypothesis: string
  suggestedChanges: string[]
  rationale: string
  impactScore: number
  confidenceScore: number
  costScore: number
  priorityScore: number
  signalSummary: Record<string, unknown>
}): HypothesisBacklogItem {
  const now = new Date().toISOString()
  return {
    id: `radar_virtual_${Date.now()}_${input.index}`,
    module: input.module,
    priority: 'critical',
    hypothesis: input.hypothesis,
    suggestedChanges: input.suggestedChanges,
    rationale: input.rationale,
    status: 'pending',
    autoGenerated: true,
    impactScore: input.impactScore,
    confidenceScore: input.confidenceScore,
    costScore: input.costScore,
    priorityScore: input.priorityScore,
    signalSummary: input.signalSummary,
    generatedAt: now,
    updatedAt: now,
  }
}

export async function GET(request: NextRequest) {
  const auth = await requireAdminUser(request, ['admin', 'lead_reviewer', 'auditor'])
  if (auth instanceof NextResponse) return auth

  const search = request.nextUrl.searchParams
  const moduleParam = search.get('module')
  const moduleFilter = moduleParam ? (moduleParam as LabModule) : undefined
  const limit = toInt(search.get('limit'), 25, 1, 200)
  const refresh = search.get('refresh') === '1'

  const manualRadarBoostModules = String(search.get('radarBoostModules') || 'scoring,pipeline,operator')
    .split(',')
    .map((x) => x.trim())
    .filter(Boolean)

  const baseUrl =
    search.get('baseUrl') || request.headers.get('origin') || 'http://127.0.0.1:3000'

  if (refresh) {
    await generateHypotheses()
  }

  const [backlog, feedback, radarSignals] = await Promise.all([
    listBacklog(moduleFilter, 500),
    listRecentUserFeedback(500),
    getRadarCycleSignals(baseUrl),
  ])

  const virtualRadarItems = radarSignals.priorityHypotheses.map((hyp, index) =>
    radarVirtualItem({
      index,
      module: hyp.module,
      hypothesis: hyp.hypothesis,
      suggestedChanges: hyp.suggestedChanges,
      rationale: hyp.rationale,
      impactScore: Number(hyp.impactScore ?? 8),
      confidenceScore: Number(hyp.confidenceScore ?? 7),
      costScore: Number(hyp.costScore ?? 3),
      priorityScore: Number(hyp.priorityScore ?? 85),
      signalSummary: {
        ...(hyp.signalSummary || {}),
        source: 'radar_virtual_preview',
      },
    })
  )

  const combinedBacklog = [...backlog, ...virtualRadarItems]
  const previousScores = await getLatestPriorityScores(combinedBacklog.map((x) => x.id))
  const decisionPenaltyByKey = await getDecisionPenaltyMap(
    combinedBacklog.map((x) => ({ module: x.module, hypothesis: x.hypothesis }))
  )

  const baselineRanked = rankBacklogForExecution(backlog, {
    recentFeedback: feedback,
    radarBoostModules: [],
    radarPriorityOverrides: {},
    previousScores,
    decisionPenaltyByKey,
  })

  const effectiveRadarBoostModules = [
    ...new Set([...manualRadarBoostModules, ...radarSignals.boostModules]),
  ]

  const previewRanked = rankBacklogForExecution(combinedBacklog, {
    recentFeedback: feedback,
    radarBoostModules: effectiveRadarBoostModules,
    radarPriorityOverrides: radarSignals.priorityOverrides,
    previousScores,
    decisionPenaltyByKey,
  })

  const baselinePosition = new Map<string, number>()
  baselineRanked.forEach((entry, idx) => {
    baselinePosition.set(backlogKey(entry.item), idx + 1)
  })

  const rankedPreview = previewRanked.slice(0, limit).map((entry, idx) => {
    const toRank = idx + 1
    const key = backlogKey(entry.item)
    const fromRank = baselinePosition.get(key) || null
    const rankDelta = fromRank ? fromRank - toRank : null

    let movement: 'up' | 'down' | 'same' | 'new' = 'new'
    if (fromRank !== null) {
      movement = rankDelta === 0 ? 'same' : rankDelta && rankDelta > 0 ? 'up' : 'down'
    }

    const reasons = [...entry.reasons]
    if (movement === 'up' && reasons.length === 0) {
      reasons.push('promoted by composite score balance (impact/confidence/urgency/cost)')
    }
    if (movement === 'down' && reasons.length === 0) {
      reasons.push('demoted by stronger competing hypotheses in current cycle context')
    }
    if (movement === 'new') {
      reasons.push('new item injected by radar bridge or newly generated backlog')
    }

    return {
      backlogId: entry.item.id,
      module: entry.item.module,
      hypothesis: entry.item.hypothesis,
      movement,
      fromRank,
      toRank,
      rankDelta,
      dynamicPriorityScore: entry.dynamicPriorityScore,
      scoreBreakdown: {
        impact: entry.impact,
        confidence: entry.confidence,
        urgency: entry.urgency,
        costPenalty: entry.costPenalty,
        momentum: entry.momentum,
        radarOverrideBoost: entry.radarOverrideBoost,
      },
      reasons,
      signalSummary: entry.item.signalSummary,
    }
  })

  return NextResponse.json({
    success: true,
    data: {
      totalBacklog: backlog.length,
      effectiveRadarBoostModules,
      radar: {
        summary: radarSignals.summary,
        boostedModules: radarSignals.boostModules,
        priorityOverrides: radarSignals.priorityOverrides,
        virtualInjections: virtualRadarItems.map((x) => ({
          module: x.module,
          hypothesis: x.hypothesis,
        })),
      },
      rankedPreview,
    },
  })
}
